[package]
name = "marlua"
version = "0.1.0"
edition = "2021"

[dependencies]
femtovg = { version = "0.6.0", features = ["glutin"] }
fastnes = { path = "fastnes" }
glutin = "0.30.7"
glutin-winit = "0.3.0"
raw-window-handle = "0.5.2"
rlua = "0.19.4"
winit = "0.28.3"
spin_sleep = "1.1.1"
